#!/bin/bash
# LocalHub - Complete Setup Summary
# This is a quick reference for getting the website running

echo "╔════════════════════════════════════════════╗"
echo "║     LocalHub E-Commerce Platform          ║"
echo "║         Complete Setup Guide              ║"
echo "╚════════════════════════════════════════════╝"
echo ""

echo "📋 SYSTEM REQUIREMENTS:"
echo "  ✓ Node.js v14+ (check: node --version)"
echo "  ✓ npm v6+ (check: npm --version)"
echo "  ✓ MongoDB v4.4+ (local or MongoDB Atlas)"
echo "  ✓ Modern Web Browser"
echo ""

echo "🚀 QUICK START (Choose One):"
echo ""
echo "Option 1: Automatic Setup (Recommended)"
echo "  Windows: setup.bat"
echo "  Mac/Linux: ./setup.sh"
echo ""
echo "Option 2: Manual Setup"
echo "  cd backend && npm install && npm start"
echo "  cd frontend && npm install && npm start  (new terminal)"
echo ""

echo "📱 ACCESS THE WEBSITE:"
echo "  Frontend: http://localhost:3000"
echo "  Backend API: http://localhost:5000/api"
echo ""

echo "👤 TEST ACCOUNTS (password: password123):"
echo "  Admin: admin@localhub.com"
echo "  Seller: seller@localhub.com"
echo "  Customer: customer@localhub.com"
echo ""

echo "💳 PAYMENT TESTING (Stripe):"
echo "  Card Number: 4242 4242 4242 4242"
echo "  Expiry: Any future date (MM/YY)"
echo "  CVC: Any 3 digits"
echo ""

echo "✅ VERIFICATION CHECKLIST:"
echo "  □ Backend running on port 5000"
echo "  □ Frontend running on port 3000"
echo "  □ MongoDB connected"
echo "  □ Can login with test accounts"
echo "  □ Can add products to cart"
echo "  □ Can complete checkout"
echo "  □ Payment processing works"
echo ""

echo "📚 DETAILED DOCS:"
echo "  Setup: Read SETUP.md"
echo "  Project: Read README.md"
echo "  API Reference: In README.md"
echo ""

echo "⚙️ CONFIGURATION FILES:"
echo "  Backend: backend/.env"
echo "  Frontend: frontend/.env"
echo ""

echo "🔧 COMMON COMMANDS:"
echo ""
echo "Start Backend:"
echo "  cd backend && npm start"
echo ""
echo "Start Frontend:"
echo "  cd frontend && npm start"
echo ""
echo "Install Dependencies:"
echo "  cd backend && npm install"
echo "  cd frontend && npm install"
echo ""
echo "Reset Database (MongoDB):"
echo "  mongosh"
echo "  use localhub"
echo "  db.dropDatabase()"
echo ""

echo "📧 EMAIL SETUP (Optional):"
echo "  Add to backend/.env:"
echo "  EMAIL_USER=your_email@gmail.com"
echo "  EMAIL_PASSWORD=your_app_password"
echo ""

echo "🌐 DEPLOYMENT:"
echo "  Frontend: Deploy with npm run build"
echo "  Backend: Deploy to Heroku/AWS/Render"
echo "  Database: Use MongoDB Atlas cloud"
echo ""

echo "❓ TROUBLESHOOTING:"
echo ""
echo "Cannot connect to MongoDB?"
echo "  1. Start MongoDB: mongod"
echo "  2. Check MONGODB_URI in backend/.env"
echo "  3. Try MongoDB Atlas instead"
echo ""
echo "Port already in use?"
echo "  Change PORT in backend/.env to 5001"
echo "  Or kill process: lsof -ti:5000 | xargs kill -9"
echo ""
echo "CORS Error?"
echo "  Update FRONTEND_URL in backend/.env"
echo "  Ensure backend & frontend are both running"
echo ""
echo "Payment not working?"
echo "  Verify Stripe keys in both .env files"
echo "  Backend must be running"
echo "  Use test card: 4242 4242 4242 4242"
echo ""

echo "🎯 NEXT STEPS:"
echo "  1. Setup the environment using setup.bat or setup.sh"
echo "  2. Start both servers (frontend & backend)"
echo "  3. Open http://localhost:3000"
echo "  4. Login with test accounts"
echo "  5. Test the complete payment flow"
echo "  6. Customize colors and content"
echo "  7. Deploy to production when ready"
echo ""

echo "📞 SUPPORT:"
echo "  API Docs: Check README.md"
echo "  Setup Issues: Check SETUP.md troubleshooting"
echo "  Code Issues: Review console errors (F12)"
echo ""

echo "╔════════════════════════════════════════════╗"
echo "║   Ready to build your ecommerce empire!   ║"
echo "╚════════════════════════════════════════════╝"
